import { VocabItem } from "./types"

const raw: Array<{ unit: string; word: string; definition: string }> = [
  // ── UNIT 1 ──────────────────────────────────────────────────────────────
  { unit: "Unit 1: Thinking Geographically", word: "Thinking Geographically", definition: "The study of the spatial arrangement of human and physical phenomena on Earth's surface and the processes that create, modify, and sustain those patterns over time." },
  { unit: "Unit 1: Thinking Geographically", word: "GPS (Global Positioning System)", definition: "A satellite-based navigation system that determines precise absolute location (latitude and longitude) anywhere on Earth by triangulating signals from multiple satellites." },
  { unit: "Unit 1: Thinking Geographically", word: "GIS (Geographic Information System)", definition: "A computer-based system that captures, stores, analyzes, and visualizes spatial and geographic data to reveal patterns, relationships, and trends." },
  { unit: "Unit 1: Thinking Geographically", word: "Spatial Approach", definition: "A method of analysis that focuses on the location, distribution, and spatial relationships of phenomena to understand why they occur where they do." },
  { unit: "Unit 1: Thinking Geographically", word: "Quantitative Data", definition: "Numerical information that can be measured and statistically analyzed, such as population totals, distances, or income levels." },
  { unit: "Unit 1: Thinking Geographically", word: "Geospatial Data", definition: "Information that is tied to a specific geographic location, including coordinates, addresses, or mapped features." },
  { unit: "Unit 1: Thinking Geographically", word: "Time-Space Compression", definition: "The reduction in the time it takes to travel between places due to advancements in transportation and communication technologies." },
  { unit: "Unit 1: Thinking Geographically", word: "Flow", definition: "The movement of people, goods, capital, or ideas across space, often along networks." },
  { unit: "Unit 1: Thinking Geographically", word: "Distance Decay", definition: "The principle that interaction between two places decreases as the distance between them increases." },
  { unit: "Unit 1: Thinking Geographically", word: "Human-Environmental Interaction", definition: "The dynamic relationship between humans and the natural environment, including how humans modify the environment and how the environment influences human activity." },
  { unit: "Unit 1: Thinking Geographically", word: "Natural Resources", definition: "Materials and components found in nature that are useful to humans, such as water, minerals, forests, and fossil fuels." },
  { unit: "Unit 1: Thinking Geographically", word: "Spatial Patterns", definition: "The arrangement and organization of phenomena across Earth's surface." },
  { unit: "Unit 1: Thinking Geographically", word: "Field Observations (Fieldwork)", definition: "The collection of primary data through direct observation, interviews, or measurements in real-world settings." },
  { unit: "Unit 1: Thinking Geographically", word: "Remote Sensing", definition: "The acquisition of information about Earth's surface using satellite or aerial imagery without direct contact." },
  { unit: "Unit 1: Thinking Geographically", word: "Clustered (Agglomerated) Distribution", definition: "A pattern in which objects or people are grouped closely together." },
  { unit: "Unit 1: Thinking Geographically", word: "Dispersed Distribution", definition: "A pattern in which objects or people are spread evenly across an area." },
  { unit: "Unit 1: Thinking Geographically", word: "Reference Map", definition: "A map that shows the locations of geographic features such as cities, roads, rivers, and political boundaries." },
  { unit: "Unit 1: Thinking Geographically", word: "Thematic Map", definition: "A map designed to display a specific type of data or theme, such as population density or climate." },
  { unit: "Unit 1: Thinking Geographically", word: "Space", definition: "The physical gap or distance between objects or places." },
  { unit: "Unit 1: Thinking Geographically", word: "Place", definition: "A specific location that has physical characteristics and human meaning attached to it." },
  { unit: "Unit 1: Thinking Geographically", word: "Location", definition: "The position of a place on Earth's surface." },
  { unit: "Unit 1: Thinking Geographically", word: "Absolute Location", definition: "The exact position of a place using coordinates such as latitude and longitude." },
  { unit: "Unit 1: Thinking Geographically", word: "Relative Location", definition: "The position of a place in relation to other places." },
  { unit: "Unit 1: Thinking Geographically", word: "Direction", definition: "The orientation of one place relative to another, often expressed using cardinal directions." },
  { unit: "Unit 1: Thinking Geographically", word: "Distance", definition: "The measurable space between two locations." },
  { unit: "Unit 1: Thinking Geographically", word: "Absolute Distance", definition: "The exact physical measurement between two locations." },
  { unit: "Unit 1: Thinking Geographically", word: "Relative Distance", definition: "The perceived or experienced distance, influenced by time, cost, or cultural factors." },
  { unit: "Unit 1: Thinking Geographically", word: "Elevation", definition: "The height of a location above sea level." },
  { unit: "Unit 1: Thinking Geographically", word: "Site", definition: "The physical characteristics of a place, including landforms, climate, and vegetation." },
  { unit: "Unit 1: Thinking Geographically", word: "Situation", definition: "The location of a place relative to its surroundings and other places." },
  { unit: "Unit 1: Thinking Geographically", word: "Sustainability", definition: "The practice of using resources in a way that does not compromise the ability of future generations to meet their needs." },
  { unit: "Unit 1: Thinking Geographically", word: "Land Use", definition: "The ways in which humans utilize land for activities such as agriculture, industry, or settlement." },
  { unit: "Unit 1: Thinking Geographically", word: "Environmental Determinism", definition: "The theory that the physical environment determines human behavior and societal development." },
  { unit: "Unit 1: Thinking Geographically", word: "Possibilism", definition: "The theory that humans can modify and adapt to their environment rather than being controlled by it." },
  { unit: "Unit 1: Thinking Geographically", word: "Scale of Analysis", definition: "The level at which data is examined, ranging from local to global." },
  { unit: "Unit 1: Thinking Geographically", word: "Region", definition: "An area defined by shared characteristics." },
  { unit: "Unit 1: Thinking Geographically", word: "Formal Region", definition: "A region defined by uniform characteristics such as language or climate." },
  { unit: "Unit 1: Thinking Geographically", word: "Functional (Nodal) Region", definition: "A region organized around a central point with surrounding areas linked to it." },
  { unit: "Unit 1: Thinking Geographically", word: "Perceptual (Vernacular) Region", definition: "A region defined by people's perceptions or beliefs." },
  { unit: "Unit 1: Thinking Geographically", word: "Physical Geography", definition: "The study of Earth's natural features and processes." },
  { unit: "Unit 1: Thinking Geographically", word: "Human Geography", definition: "The study of human populations, cultures, and activities and their spatial relationships." },
  { unit: "Unit 1: Thinking Geographically", word: "Model", definition: "A simplified representation of reality used to explain patterns or processes." },
  { unit: "Unit 1: Thinking Geographically", word: "Spatial Model", definition: "A model that focuses on geographic patterns and relationships." },
  { unit: "Unit 1: Thinking Geographically", word: "Nonspatial Model", definition: "A model that explains processes without focusing on location." },
  { unit: "Unit 1: Thinking Geographically", word: "Networks", definition: "Systems of interconnected nodes and links through which flows occur." },
  { unit: "Unit 1: Thinking Geographically", word: "Qualitative Data", definition: "Non-numerical information such as descriptions, observations, or interviews." },
  { unit: "Unit 1: Thinking Geographically", word: "Choropleth Map", definition: "A thematic map that uses shading or color to represent statistical data." },
  { unit: "Unit 1: Thinking Geographically", word: "Dot Distribution Map", definition: "A map that uses dots to represent the occurrence of a feature." },
  { unit: "Unit 1: Thinking Geographically", word: "Graduated Symbol Map", definition: "A map that uses symbols of varying sizes to represent data." },
  { unit: "Unit 1: Thinking Geographically", word: "Isoline Map", definition: "A map that connects points of equal value with lines." },
  { unit: "Unit 1: Thinking Geographically", word: "Cartogram", definition: "A map that distorts geographic size to represent data values." },
  { unit: "Unit 1: Thinking Geographically", word: "Map Scale", definition: "The ratio between distances on a map and actual distances on Earth." },
  { unit: "Unit 1: Thinking Geographically", word: "Small-Scale Map", definition: "Shows a large area with less detail." },
  { unit: "Unit 1: Thinking Geographically", word: "Large-Scale Map", definition: "Shows a small area with more detail." },
  { unit: "Unit 1: Thinking Geographically", word: "Latitude", definition: "Lines measuring distance north or south of the equator." },
  { unit: "Unit 1: Thinking Geographically", word: "Longitude", definition: "Lines measuring distance east or west of the prime meridian." },
  { unit: "Unit 1: Thinking Geographically", word: "Equator", definition: "The line at 0° latitude dividing the Earth into Northern and Southern Hemispheres." },
  { unit: "Unit 1: Thinking Geographically", word: "Prime Meridian", definition: "The line at 0° longitude dividing the Earth into Eastern and Western Hemispheres." },
  { unit: "Unit 1: Thinking Geographically", word: "International Date Line", definition: "The line where the calendar date changes by one day." },
  { unit: "Unit 1: Thinking Geographically", word: "Projection", definition: "A method of representing Earth's curved surface on a flat map." },
  { unit: "Unit 1: Thinking Geographically", word: "Mercator Projection", definition: "Preserves direction but distorts size, especially near the poles." },
  { unit: "Unit 1: Thinking Geographically", word: "Peters Projection", definition: "Preserves area but distorts shape." },
  { unit: "Unit 1: Thinking Geographically", word: "Robinson Projection", definition: "Attempts to balance distortions of area, shape, distance, and direction." },
  { unit: "Unit 1: Thinking Geographically", word: "Friction of Distance", definition: "The increase in cost, time, and effort as distance increases." },
  { unit: "Unit 1: Thinking Geographically", word: "Cultural Landscape", definition: "The visible imprint of human activity on the landscape." },

  // ── UNIT 2 ──────────────────────────────────────────────────────────────
  { unit: "Unit 2: Population & Migration", word: "Population Distribution", definition: "The spatial pattern of where people live across Earth's surface." },
  { unit: "Unit 2: Population & Migration", word: "Population Density", definition: "The number of people per unit of area." },
  { unit: "Unit 2: Population & Migration", word: "Arithmetic Density", definition: "Total population divided by total land area." },
  { unit: "Unit 2: Population & Migration", word: "Physiological Density", definition: "Number of people per unit of arable land, indicating pressure on food supply." },
  { unit: "Unit 2: Population & Migration", word: "Agricultural Density", definition: "Number of farmers per unit of arable land." },
  { unit: "Unit 2: Population & Migration", word: "Carrying Capacity", definition: "The maximum population size that an environment can sustainably support." },
  { unit: "Unit 2: Population & Migration", word: "Population Pyramid", definition: "A graph showing the distribution of a population by age and sex." },
  { unit: "Unit 2: Population & Migration", word: "Total Fertility Rate (TFR)", definition: "The average number of children a woman is expected to have during her lifetime." },
  { unit: "Unit 2: Population & Migration", word: "Infant Mortality Rate (IMR)", definition: "The number of deaths of infants under age one per 1,000 live births." },
  { unit: "Unit 2: Population & Migration", word: "Rate of Natural Increase (RNI)", definition: "The percentage growth of a population excluding migration (CBR − CDR)." },
  { unit: "Unit 2: Population & Migration", word: "Dependency Ratio", definition: "The ratio of dependents (young and old) to the working-age population." },
  { unit: "Unit 2: Population & Migration", word: "Population Doubling Time", definition: "The time required for a population to double in size." },
  { unit: "Unit 2: Population & Migration", word: "Demographic Transition Model (DTM)", definition: "A model describing population change over time through stages based on birth and death rates." },
  { unit: "Unit 2: Population & Migration", word: "Epidemiological Transition Model", definition: "A model describing changes in disease patterns as a country develops." },
  { unit: "Unit 2: Population & Migration", word: "Malthusian Theory", definition: "The idea that population grows faster than food supply, leading to crisis." },
  { unit: "Unit 2: Population & Migration", word: "Pronatalist Policies", definition: "Government policies designed to encourage higher birth rates." },
  { unit: "Unit 2: Population & Migration", word: "Antinatalist Policies", definition: "Policies designed to reduce birth rates." },
  { unit: "Unit 2: Population & Migration", word: "Migration", definition: "The permanent relocation of people from one place to another." },
  { unit: "Unit 2: Population & Migration", word: "Voluntary Migration", definition: "Migration by choice." },
  { unit: "Unit 2: Population & Migration", word: "Forced Migration", definition: "Migration in which people are compelled to move." },
  { unit: "Unit 2: Population & Migration", word: "Push Factors", definition: "Conditions that drive people to leave a place." },
  { unit: "Unit 2: Population & Migration", word: "Pull Factors", definition: "Conditions that attract people to a place." },
  { unit: "Unit 2: Population & Migration", word: "Intervening Obstacles", definition: "Barriers that hinder migration." },
  { unit: "Unit 2: Population & Migration", word: "Intervening Opportunities", definition: "Alternative destinations that arise during migration." },
  { unit: "Unit 2: Population & Migration", word: "Step Migration", definition: "Migration in a series of smaller moves." },
  { unit: "Unit 2: Population & Migration", word: "Rural-to-Urban Migration", definition: "Movement from countryside to cities." },
  { unit: "Unit 2: Population & Migration", word: "Ravenstein's Laws", definition: "Principles explaining migration patterns including short distances and step migration." },
  { unit: "Unit 2: Population & Migration", word: "Internally Displaced Persons (IDPs)", definition: "People forced to move within their country." },
  { unit: "Unit 2: Population & Migration", word: "Refugee", definition: "Someone forced to flee their country due to danger." },
  { unit: "Unit 2: Population & Migration", word: "Asylum", definition: "Legal protection granted to refugees." },
  { unit: "Unit 2: Population & Migration", word: "Internal Migration", definition: "Movement within a country." },
  { unit: "Unit 2: Population & Migration", word: "Transnational Migration", definition: "Movement across national borders." },
  { unit: "Unit 2: Population & Migration", word: "Chain Migration", definition: "Migration of people to a location where family members already live." },
  { unit: "Unit 2: Population & Migration", word: "Guest Workers", definition: "Foreign workers allowed into a country temporarily." },
  { unit: "Unit 2: Population & Migration", word: "Transhumance", definition: "Seasonal migration of livestock." },
  { unit: "Unit 2: Population & Migration", word: "Social Stratification", definition: "The division of society into classes." },
  { unit: "Unit 2: Population & Migration", word: "Arable Land", definition: "Land suitable for agriculture." },
  { unit: "Unit 2: Population & Migration", word: "Overpopulation", definition: "When population exceeds the capacity of the environment." },
  { unit: "Unit 2: Population & Migration", word: "Baby Boom", definition: "A period of unusually high birth rates." },
  { unit: "Unit 2: Population & Migration", word: "Birth Deficit", definition: "When deaths exceed births." },
  { unit: "Unit 2: Population & Migration", word: "Immigrant", definition: "A person entering a country." },
  { unit: "Unit 2: Population & Migration", word: "Emigrant", definition: "A person leaving a country." },
  { unit: "Unit 2: Population & Migration", word: "Crude Birth Rate (CBR)", definition: "Births per 1,000 people." },
  { unit: "Unit 2: Population & Migration", word: "Crude Death Rate (CDR)", definition: "Deaths per 1,000 people." },
  { unit: "Unit 2: Population & Migration", word: "Life Expectancy", definition: "The average number of years a person is expected to live." },
  { unit: "Unit 2: Population & Migration", word: "Demographic Momentum", definition: "Continued population growth after fertility declines." },
  { unit: "Unit 2: Population & Migration", word: "Gravity Model of Migration", definition: "Predicts migration based on population size and distance." },
  { unit: "Unit 2: Population & Migration", word: "Counter Migration", definition: "Returning to one's original location." },
  { unit: "Unit 2: Population & Migration", word: "Remittances", definition: "Money sent by migrants to their home country." },
  { unit: "Unit 2: Population & Migration", word: "Brain Drain", definition: "Loss of educated or skilled workers from a country." },
  { unit: "Unit 2: Population & Migration", word: "Ethnic Enclaves", definition: "Areas where people of similar ethnicity live together." },

  // ── UNIT 3 ──────────────────────────────────────────────────────────────
  { unit: "Unit 3: Culture", word: "Culture", definition: "The set of shared practices, technologies, attitudes, and behaviors transmitted by a society. It includes material and nonmaterial elements that shape how people live and interpret the world." },
  { unit: "Unit 3: Culture", word: "Cultural Traits", definition: "Individual elements of culture such as language, food preferences, clothing, or religious practices." },
  { unit: "Unit 3: Culture", word: "Cultural Complex", definition: "A combination of interrelated cultural traits that function together within a society." },
  { unit: "Unit 3: Culture", word: "Placelessness", definition: "The loss of unique characteristics of a place, often due to globalization and standardized landscapes." },
  { unit: "Unit 3: Culture", word: "Traditional Architecture", definition: "Building styles that reflect local culture, materials, climate, and traditions." },
  { unit: "Unit 3: Culture", word: "Postmodern Architecture", definition: "Contemporary architectural style that often blends historical styles, symbolism, and diverse designs." },
  { unit: "Unit 3: Culture", word: "Ethnicity", definition: "Shared identity based on common ancestry, language, religion, or cultural traditions." },
  { unit: "Unit 3: Culture", word: "Sequent Occupance", definition: "The idea that successive societies leave their cultural imprints on a place over time." },
  { unit: "Unit 3: Culture", word: "Cultural Patterns", definition: "The spatial distribution and organization of cultural traits." },
  { unit: "Unit 3: Culture", word: "Centripetal Forces", definition: "Forces that unify a society, such as shared language, religion, or national identity." },
  { unit: "Unit 3: Culture", word: "Centrifugal Forces", definition: "Forces that divide a society, such as ethnic conflict, political differences, or economic inequality." },
  { unit: "Unit 3: Culture", word: "Ethnocentrism", definition: "The belief that one's own culture is superior to others." },
  { unit: "Unit 3: Culture", word: "Cultural Relativism", definition: "The practice of understanding a culture on its own terms without judgment." },
  { unit: "Unit 3: Culture", word: "Cultural Landscape", definition: "The visible imprint of human activity and culture on the physical environment." },
  { unit: "Unit 3: Culture", word: "Relocation Diffusion", definition: "The spread of culture through the physical movement of people." },
  { unit: "Unit 3: Culture", word: "Expansion Diffusion", definition: "The spread of a cultural trait through a population, from its source outward." },
  { unit: "Unit 3: Culture", word: "Contagious Diffusion", definition: "Rapid, widespread diffusion that spreads like a disease through direct contact." },
  { unit: "Unit 3: Culture", word: "Hierarchical Diffusion", definition: "The spread of culture from authorities or influential people to others." },
  { unit: "Unit 3: Culture", word: "Imperialism", definition: "The extension of a country's power over other territories through economic, political, or military means." },
  { unit: "Unit 3: Culture", word: "Colonialism", definition: "The establishment and maintenance of political control over a foreign territory." },
  { unit: "Unit 3: Culture", word: "Lingua Franca", definition: "A common language used for communication between speakers of different native languages." },
  { unit: "Unit 3: Culture", word: "Creole Language", definition: "A stable language that develops from the mixing of parent languages and becomes native to a population." },
  { unit: "Unit 3: Culture", word: "Time-Space Convergence", definition: "The decreasing time needed to travel between places due to technological improvements." },
  { unit: "Unit 3: Culture", word: "Cultural Convergence", definition: "The process in which cultures become more similar due to globalization." },
  { unit: "Unit 3: Culture", word: "Cultural Divergence", definition: "The process in which cultures become more distinct from one another." },
  { unit: "Unit 3: Culture", word: "Globalization", definition: "The increasing interconnectedness of the world through economic, cultural, and technological exchange." },
  { unit: "Unit 3: Culture", word: "Language Tree Model", definition: "A model showing how languages branch from common ancestors." },
  { unit: "Unit 3: Culture", word: "Language Family", definition: "A group of languages descended from a common ancestor." },
  { unit: "Unit 3: Culture", word: "Language Branch", definition: "A subdivision of a language family." },
  { unit: "Unit 3: Culture", word: "Indo-European Language Family", definition: "A major language family that includes most languages spoken in Europe and parts of Asia." },
  { unit: "Unit 3: Culture", word: "Dialect", definition: "A regional variation of a language distinguished by vocabulary, grammar, or pronunciation." },
  { unit: "Unit 3: Culture", word: "Toponym", definition: "The name of a place derived from its physical or cultural characteristics." },
  { unit: "Unit 3: Culture", word: "Ethnic Religion", definition: "A religion closely tied to a specific ethnic group or geographic location." },
  { unit: "Unit 3: Culture", word: "Universalizing Religion", definition: "A religion that actively seeks converts worldwide." },
  { unit: "Unit 3: Culture", word: "Hinduism", definition: "A major ethnic religion originating in India, characterized by reincarnation and karma." },
  { unit: "Unit 3: Culture", word: "Buddhism", definition: "A universalizing religion based on the teachings of Siddhartha Gautama." },
  { unit: "Unit 3: Culture", word: "Sikhism", definition: "A monotheistic religion originating in the Punjab region emphasizing equality and devotion." },
  { unit: "Unit 3: Culture", word: "Judaism", definition: "An ethnic monotheistic religion originating in the ancient Middle East." },
  { unit: "Unit 3: Culture", word: "Christianity", definition: "A universalizing religion based on the teachings of Jesus Christ." },
  { unit: "Unit 3: Culture", word: "Islam", definition: "A universalizing monotheistic religion based on the teachings of Muhammad." },
  { unit: "Unit 3: Culture", word: "Acculturation", definition: "The process of adopting some traits of another culture while retaining one's own identity." },
  { unit: "Unit 3: Culture", word: "Assimilation", definition: "The complete adoption of another culture, resulting in the loss of original cultural identity." },
  { unit: "Unit 3: Culture", word: "Syncretism", definition: "The blending of two or more cultural or religious traditions into a new system." },
  { unit: "Unit 3: Culture", word: "Multiculturalism", definition: "The coexistence of multiple cultures within a society." },
  { unit: "Unit 3: Culture", word: "Cultural Hearth", definition: "A region where a culture originates and from which it spreads." },
  { unit: "Unit 3: Culture", word: "Taboo", definition: "A social or cultural restriction on behavior considered inappropriate or forbidden." },
  { unit: "Unit 3: Culture", word: "Folk Culture", definition: "Traditional culture practiced by small, isolated groups." },
  { unit: "Unit 3: Culture", word: "Popular Culture", definition: "Cultural traits that are widespread and rapidly changing, often spread through mass media." },
  { unit: "Unit 3: Culture", word: "Artifacts", definition: "Physical objects created by a culture." },
  { unit: "Unit 3: Culture", word: "Mentifacts", definition: "Ideas, beliefs, and values of a culture." },
  { unit: "Unit 3: Culture", word: "Sociofacts", definition: "Institutions and structures that organize society." },
  { unit: "Unit 3: Culture", word: "Built Environment", definition: "Human-made surroundings such as buildings and infrastructure." },
  { unit: "Unit 3: Culture", word: "Diaspora", definition: "The dispersion of a population from its original homeland." },
  { unit: "Unit 3: Culture", word: "Neolocalism", definition: "A movement encouraging people to reconnect with local culture and identity." },
  { unit: "Unit 3: Culture", word: "Nationality", definition: "Legal membership in a nation-state." },
  { unit: "Unit 3: Culture", word: "Fundamentalism", definition: "Strict adherence to religious doctrines." },
  { unit: "Unit 3: Culture", word: "Theocracy", definition: "A government controlled by religious leaders." },
  { unit: "Unit 3: Culture", word: "Cultural Appropriation", definition: "The adoption of elements of one culture by another, often without understanding or respect." },
  { unit: "Unit 3: Culture", word: "Animism", definition: "The belief that objects, places, and creatures have spiritual essence." },
  { unit: "Unit 3: Culture", word: "Native Speaker", definition: "A person who learns a language from early childhood." },
  { unit: "Unit 3: Culture", word: "Slang", definition: "Informal language used within groups." },
  { unit: "Unit 3: Culture", word: "Pidgin Language", definition: "A simplified language developed for communication between speakers of different languages." },
  { unit: "Unit 3: Culture", word: "Romance Languages", definition: "Languages derived from Latin such as Spanish, French, and Italian." },
  { unit: "Unit 3: Culture", word: "Isogloss", definition: "A boundary separating regions with different linguistic features." },
  { unit: "Unit 3: Culture", word: "Official Language", definition: "A language given legal status for government use." },
  { unit: "Unit 3: Culture", word: "Homogeneous", definition: "Uniform or similar in nature." },
  { unit: "Unit 3: Culture", word: "Homogenization", definition: "The process by which cultures become more similar." },
  { unit: "Unit 3: Culture", word: "Adherent", definition: "A follower of a particular religion." },
  { unit: "Unit 3: Culture", word: "Polytheistic", definition: "Belief in multiple gods." },
  { unit: "Unit 3: Culture", word: "Monotheistic", definition: "Belief in one god." },
  { unit: "Unit 3: Culture", word: "Caste System", definition: "A rigid social hierarchy based on birth." },
  { unit: "Unit 3: Culture", word: "Pilgrimage", definition: "A journey to a sacred place for religious reasons." },
  { unit: "Unit 3: Culture", word: "Nativism", definition: "Policy or belief favoring native-born people over immigrants." },

  // ── UNIT 4 ──────────────────────────────────────────────────────────────
  { unit: "Unit 4: Politics", word: "State", definition: "A politically organized territory with a permanent population, defined borders, and sovereignty." },
  { unit: "Unit 4: Politics", word: "Sovereignty", definition: "The full control a state has over its territory and independence from external authority." },
  { unit: "Unit 4: Politics", word: "Nation", definition: "A group of people with shared culture, language, history, or identity." },
  { unit: "Unit 4: Politics", word: "Nation-State", definition: "A state whose population shares a strong cultural or ethnic identity." },
  { unit: "Unit 4: Politics", word: "Stateless Nation", definition: "A nation without its own independent state." },
  { unit: "Unit 4: Politics", word: "Multinational State", definition: "A state containing multiple nations." },
  { unit: "Unit 4: Politics", word: "Autonomous Region", definition: "A region with partial self-governance." },
  { unit: "Unit 4: Politics", word: "Semi-Autonomous Region", definition: "An area with limited but significant independence." },
  { unit: "Unit 4: Politics", word: "Multi-State Nation", definition: "A nation spread across more than one country." },
  { unit: "Unit 4: Politics", word: "Imperialism", definition: "Control of one country over another through political or economic domination." },
  { unit: "Unit 4: Politics", word: "Colonialism", definition: "Establishment of control over a territory and its people." },
  { unit: "Unit 4: Politics", word: "Berlin Conference (1884)", definition: "Meeting where European powers divided Africa without African input." },
  { unit: "Unit 4: Politics", word: "Self-Determination", definition: "The right of a people to choose their own political status." },
  { unit: "Unit 4: Politics", word: "Decolonization", definition: "The process of colonies gaining independence." },
  { unit: "Unit 4: Politics", word: "Devolution", definition: "Transfer of power from central government to regional governments." },
  { unit: "Unit 4: Politics", word: "Territoriality", definition: "The attempt by individuals or groups to control a specific area." },
  { unit: "Unit 4: Politics", word: "Neocolonialism", definition: "Economic control of developing countries by developed countries." },
  { unit: "Unit 4: Politics", word: "Choke Point", definition: "A narrow passage critical for trade or military movement." },
  { unit: "Unit 4: Politics", word: "Antecedent Boundary", definition: "A boundary drawn before significant population settlement." },
  { unit: "Unit 4: Politics", word: "Subsequent Boundary", definition: "A boundary that develops after cultural or settlement patterns exist." },
  { unit: "Unit 4: Politics", word: "Superimposed Boundary", definition: "A boundary forced onto a region without regard to cultural divisions." },
  { unit: "Unit 4: Politics", word: "Relic Boundary", definition: "A boundary that no longer functions but still exists on maps." },
  { unit: "Unit 4: Politics", word: "Geometric Boundary", definition: "A boundary drawn using straight lines." },
  { unit: "Unit 4: Politics", word: "Definitional Boundary Dispute", definition: "Disagreement over the interpretation of a boundary." },
  { unit: "Unit 4: Politics", word: "Locational Boundary Dispute", definition: "Disagreement over where a boundary is located." },
  { unit: "Unit 4: Politics", word: "Operational Boundary Dispute", definition: "Conflict over how a boundary is managed." },
  { unit: "Unit 4: Politics", word: "Allocational Boundary Dispute", definition: "Dispute over resources along a boundary." },
  { unit: "Unit 4: Politics", word: "Irredentism", definition: "Effort by a country to reclaim territory it considers historically or ethnically its own." },
  { unit: "Unit 4: Politics", word: "Demilitarized Zone (DMZ)", definition: "Area where military forces are not allowed." },
  { unit: "Unit 4: Politics", word: "Shatterbelt", definition: "Region caught between stronger opposing states." },
  { unit: "Unit 4: Politics", word: "UNCLOS", definition: "International agreement defining maritime rights." },
  { unit: "Unit 4: Politics", word: "Territorial Sea", definition: "Waters extending 12 nautical miles from a coast." },
  { unit: "Unit 4: Politics", word: "Exclusive Economic Zone (EEZ)", definition: "Area up to 200 nautical miles where a state controls resources." },
  { unit: "Unit 4: Politics", word: "Federal State", definition: "Power is shared between national and regional governments." },
  { unit: "Unit 4: Politics", word: "Unitary State", definition: "Central government holds most power." },
  { unit: "Unit 4: Politics", word: "Ethnic Separatism", definition: "Movement for independence based on ethnicity." },
  { unit: "Unit 4: Politics", word: "Terrorism", definition: "Use of violence to achieve political goals." },
  { unit: "Unit 4: Politics", word: "Supranationalism", definition: "Cooperation among multiple states (e.g., EU)." },
  { unit: "Unit 4: Politics", word: "Gerrymandering", definition: "Manipulating electoral boundaries for political advantage." },
  { unit: "Unit 4: Politics", word: "Electorate", definition: "All eligible voters." },
  { unit: "Unit 4: Politics", word: "Census", definition: "Official population count." },
  { unit: "Unit 4: Politics", word: "Reapportionment", definition: "Redistribution of political representation." },
  { unit: "Unit 4: Politics", word: "Annexation", definition: "Incorporation of territory into another state." },
  { unit: "Unit 4: Politics", word: "Balkanization", definition: "Fragmentation of a region into smaller states." },
  { unit: "Unit 4: Politics", word: "Geopolitics", definition: "Study of politics influenced by geography." },
  { unit: "Unit 4: Politics", word: "Nationalism", definition: "Strong identification with one's nation." },
  { unit: "Unit 4: Politics", word: "Genocide", definition: "Systematic destruction of a group." },
  { unit: "Unit 4: Politics", word: "Cold War", definition: "Political tension between the U.S. and USSR." },

  // ── UNIT 5 ──────────────────────────────────────────────────────────────
  { unit: "Unit 5: Agriculture", word: "Agriculture", definition: "The deliberate modification of Earth's surface through cultivation of plants and rearing of animals to produce food, fiber, and other products." },
  { unit: "Unit 5: Agriculture", word: "Climate", definition: "Long-term average weather conditions of a place, including temperature and precipitation patterns." },
  { unit: "Unit 5: Agriculture", word: "Mediterranean Climate", definition: "A climate with hot, dry summers and mild, wet winters, typically found on west coasts between 30°–45° latitude." },
  { unit: "Unit 5: Agriculture", word: "Tropical Climate", definition: "A climate characterized by high temperatures year-round and significant rainfall, typically near the equator." },
  { unit: "Unit 5: Agriculture", word: "Intensive Agriculture", definition: "Farming that uses high inputs of labor, capital, or technology on relatively small land areas to maximize yield." },
  { unit: "Unit 5: Agriculture", word: "Extensive Agriculture", definition: "Farming that uses large land areas with relatively low inputs of labor or capital per unit of land." },
  { unit: "Unit 5: Agriculture", word: "Subsistence Agriculture", definition: "Agricultural production primarily for the farmer's own consumption, with little surplus for trade." },
  { unit: "Unit 5: Agriculture", word: "Commercial Agriculture", definition: "Farming focused on producing crops and livestock for sale in markets rather than personal use." },
  { unit: "Unit 5: Agriculture", word: "Pastoral Nomadism", definition: "A form of subsistence agriculture where people move their livestock seasonally in search of grazing land." },
  { unit: "Unit 5: Agriculture", word: "Shifting Cultivation", definition: "A farming system in which land is cleared, used for a few years, and then abandoned for soil recovery." },
  { unit: "Unit 5: Agriculture", word: "Plantation Agriculture", definition: "Large-scale commercial farming specializing in a single cash crop, often in tropical regions." },
  { unit: "Unit 5: Agriculture", word: "Mixed Crop and Livestock Farming", definition: "Agricultural system that integrates crop production and animal husbandry on the same farm." },
  { unit: "Unit 5: Agriculture", word: "Market Gardening", definition: "Intensive small-scale production of fruits, vegetables, and flowers for sale in local markets." },
  { unit: "Unit 5: Agriculture", word: "Ranching", definition: "Commercial livestock production over large areas of land." },
  { unit: "Unit 5: Agriculture", word: "Clustered Settlement", definition: "A pattern in which houses and buildings are grouped closely together." },
  { unit: "Unit 5: Agriculture", word: "Dispersed Settlement", definition: "A settlement pattern where houses are spread out over a large area." },
  { unit: "Unit 5: Agriculture", word: "Linear Settlement", definition: "Settlement pattern arranged in a line, often along roads, rivers, or valleys." },
  { unit: "Unit 5: Agriculture", word: "Metes and Bounds System", definition: "A land survey system using natural features and measurements to define property boundaries." },
  { unit: "Unit 5: Agriculture", word: "Township and Range System", definition: "A grid-based land division system used in the United States." },
  { unit: "Unit 5: Agriculture", word: "Long-Lot System", definition: "A land division system with long narrow plots extending from rivers or roads." },
  { unit: "Unit 5: Agriculture", word: "Agricultural Hearth", definition: "Geographic regions where agriculture first developed independently." },
  { unit: "Unit 5: Agriculture", word: "Fertile Crescent", definition: "A region in the Middle East where early agriculture and civilization developed." },
  { unit: "Unit 5: Agriculture", word: "Columbian Exchange", definition: "The transfer of plants, animals, diseases, and technology between the Americas and Europe after 1492." },
  { unit: "Unit 5: Agriculture", word: "First Agricultural Revolution", definition: "Transition from hunting-gathering to plant and animal domestication." },
  { unit: "Unit 5: Agriculture", word: "Second Agricultural Revolution", definition: "Period of agricultural innovation in Europe involving mechanization and improved farming techniques that increased productivity." },
  { unit: "Unit 5: Agriculture", word: "Irrigation", definition: "Artificial application of water to land to assist in crop production." },
  { unit: "Unit 5: Agriculture", word: "Green Revolution", definition: "Introduction of high-yield crops, fertilizers, and modern farming techniques in developing countries." },
  { unit: "Unit 5: Agriculture", word: "Genetically Modified Organisms (GMOs)", definition: "Crops whose genetic material has been altered to improve yield or resistance." },
  { unit: "Unit 5: Agriculture", word: "Bid-Rent Theory", definition: "Model explaining how land value and usage vary depending on distance from a central place." },
  { unit: "Unit 5: Agriculture", word: "Monoculture", definition: "The cultivation of a single crop over a large area." },
  { unit: "Unit 5: Agriculture", word: "Monocropping", definition: "Repeatedly growing the same crop on the same land." },
  { unit: "Unit 5: Agriculture", word: "Economies of Scale", definition: "Cost advantages gained by increasing production." },
  { unit: "Unit 5: Agriculture", word: "Commodity Chain", definition: "The network linking production, processing, distribution, and consumption of goods." },
  { unit: "Unit 5: Agriculture", word: "Von Thünen Model", definition: "A model explaining agricultural land use based on distance from a market center." },
  { unit: "Unit 5: Agriculture", word: "Global Supply Chain", definition: "Worldwide system of production and distribution of goods." },
  { unit: "Unit 5: Agriculture", word: "Fair Trade Movement", definition: "Effort to ensure fair wages and ethical conditions for producers in developing countries." },
  { unit: "Unit 5: Agriculture", word: "Desertification", definition: "Land degradation in arid regions due to climate change or human activity." },
  { unit: "Unit 5: Agriculture", word: "Soil Salinization", definition: "Accumulation of salts in soil, reducing fertility." },
  { unit: "Unit 5: Agriculture", word: "Terrace Farming", definition: "Farming method using stepped levels on hillsides to reduce erosion." },
  { unit: "Unit 5: Agriculture", word: "Deforestation", definition: "Large-scale removal of forests for agriculture or development." },
  { unit: "Unit 5: Agriculture", word: "Slash-and-Burn Agriculture", definition: "Method of clearing land by cutting and burning vegetation." },
  { unit: "Unit 5: Agriculture", word: "Organic Farming", definition: "Agricultural system that avoids synthetic chemicals and emphasizes natural processes." },
  { unit: "Unit 5: Agriculture", word: "Food Insecurity", definition: "Lack of reliable access to sufficient and nutritious food." },
  { unit: "Unit 5: Agriculture", word: "Food Desert", definition: "Urban or rural area with limited access to affordable healthy food." },
  { unit: "Unit 5: Agriculture", word: "Milk Shed", definition: "Region supplying milk to a specific urban market." },
  { unit: "Unit 5: Agriculture", word: "Crop Rotation", definition: "Alternating crops in a field to maintain soil fertility." },
  { unit: "Unit 5: Agriculture", word: "Agribusiness", definition: "Large-scale corporate farming and food production system." },

  // ── UNIT 6 ──────────────────────────────────────────────────────────────
  { unit: "Unit 6: Urbanization", word: "Urbanization", definition: "The increase in the percentage of people living in urban areas and the expansion of cities." },
  { unit: "Unit 6: Urbanization", word: "Suburbanization", definition: "Movement of population from urban centers to surrounding suburban areas." },
  { unit: "Unit 6: Urbanization", word: "Urban Sprawl", definition: "Unplanned outward expansion of urban areas into rural land." },
  { unit: "Unit 6: Urbanization", word: "Boomburb", definition: "Rapidly growing suburban city with over 100,000 residents." },
  { unit: "Unit 6: Urbanization", word: "Edge City", definition: "A major concentration of business and retail outside a traditional downtown." },
  { unit: "Unit 6: Urbanization", word: "Decentralization", definition: "Movement of population, jobs, and services away from central cities." },
  { unit: "Unit 6: Urbanization", word: "Exurbs", definition: "Wealthy residential areas beyond suburbs with rural characteristics." },
  { unit: "Unit 6: Urbanization", word: "Megacity", definition: "Urban area with over 10 million people." },
  { unit: "Unit 6: Urbanization", word: "Metacity", definition: "Extremely large urban area, often over 20 million people." },
  { unit: "Unit 6: Urbanization", word: "World City (Global City)", definition: "A city that functions as a major center of global finance, culture, and politics." },
  { unit: "Unit 6: Urbanization", word: "Urban Hierarchy", definition: "Ranking of cities based on size and services." },
  { unit: "Unit 6: Urbanization", word: "Rank-Size Rule", definition: "Pattern where city size is inversely proportional to its rank." },
  { unit: "Unit 6: Urbanization", word: "Primate City", definition: "A city that is disproportionately larger and more influential than others in its country." },
  { unit: "Unit 6: Urbanization", word: "Gravity Model", definition: "Predicts interaction between places based on population size and distance." },
  { unit: "Unit 6: Urbanization", word: "Central Place Theory", definition: "Explains the distribution of services based on market areas." },
  { unit: "Unit 6: Urbanization", word: "Bid-Rent Theory", definition: "Explains how land value decreases with distance from the CBD." },
  { unit: "Unit 6: Urbanization", word: "Concentric Zone Model", definition: "Urban model showing rings of land use around the CBD." },
  { unit: "Unit 6: Urbanization", word: "Sector Model", definition: "Urban model showing wedge-shaped growth along transport routes." },
  { unit: "Unit 6: Urbanization", word: "Multiple Nuclei Model", definition: "Urban model with multiple centers of activity." },
  { unit: "Unit 6: Urbanization", word: "Galactic City Model", definition: "Modern urban model with decentralized suburban business centers." },
  { unit: "Unit 6: Urbanization", word: "Disamenity Zone", definition: "Area of city with poorest housing and environmental conditions." },
  { unit: "Unit 6: Urbanization", word: "Squatter Settlement", definition: "Informal housing built without legal ownership." },
  { unit: "Unit 6: Urbanization", word: "Low-Density Housing", definition: "Residential areas with few houses per land area." },
  { unit: "Unit 6: Urbanization", word: "High-Density Housing", definition: "Areas with many people living in limited space." },
  { unit: "Unit 6: Urbanization", word: "Urban Infill", definition: "Development of unused land within cities." },
  { unit: "Unit 6: Urbanization", word: "Public Transportation", definition: "Systems such as buses, trains, and subways used for mass transit." },
  { unit: "Unit 6: Urbanization", word: "Smart Growth Policies", definition: "Urban planning strategies to reduce sprawl and promote sustainability." },
  { unit: "Unit 6: Urbanization", word: "Greenbelts", definition: "Protected land around cities to limit expansion." },
  { unit: "Unit 6: Urbanization", word: "New Urbanism", definition: "Urban design promoting walkable, mixed-use neighborhoods." },
  { unit: "Unit 6: Urbanization", word: "Mixed-Use Development", definition: "Areas combining residential, commercial, and recreational uses." },
  { unit: "Unit 6: Urbanization", word: "Walkability", definition: "Ease of walking within an urban area." },
  { unit: "Unit 6: Urbanization", word: "Livability", definition: "Quality of life in a city based on safety, services, and environment." },
  { unit: "Unit 6: Urbanization", word: "Redlining", definition: "Discriminatory practice of denying services based on race or area." },
  { unit: "Unit 6: Urbanization", word: "Blockbusting", definition: "Practice of encouraging property sales by promoting racial change fears." },
  { unit: "Unit 6: Urbanization", word: "Gentrification", definition: "Process where wealthier residents move into lower-income neighborhoods." },
  { unit: "Unit 6: Urbanization", word: "Environmental Injustice", definition: "Unequal exposure of minority communities to environmental hazards." },
  { unit: "Unit 6: Urbanization", word: "Ecological Footprint", definition: "Measure of human demand on Earth's ecosystems." },
  { unit: "Unit 6: Urbanization", word: "Brownfields", definition: "Abandoned industrial sites often requiring cleanup." },
  { unit: "Unit 6: Urbanization", word: "Ecumene", definition: "Densely inhabited areas of the world." },
  { unit: "Unit 6: Urbanization", word: "Counter-Urbanization", definition: "Movement of people from cities to rural areas." },
  { unit: "Unit 6: Urbanization", word: "Megalopolis", definition: "Large chain of connected metropolitan areas." },
  { unit: "Unit 6: Urbanization", word: "Central Business District (CBD)", definition: "Commercial core of a city." },
  { unit: "Unit 6: Urbanization", word: "Threshold", definition: "Minimum number of customers needed for a service to exist." },
  { unit: "Unit 6: Urbanization", word: "Range", definition: "Maximum distance people will travel to use a service." },
  { unit: "Unit 6: Urbanization", word: "Zoning Ordinances", definition: "Laws regulating land use in cities." },
  { unit: "Unit 6: Urbanization", word: "Urban Renewal", definition: "Redevelopment of deteriorated urban areas." },
  { unit: "Unit 6: Urbanization", word: "Eminent Domain", definition: "Government power to take private land for public use." },

  // ── UNIT 7 ──────────────────────────────────────────────────────────────
  { unit: "Unit 7: Industrialization", word: "Industrialization", definition: "Process of economic and social change where manufacturing becomes dominant." },
  { unit: "Unit 7: Industrialization", word: "Primary Sector", definition: "Economic activities involving extraction of natural resources." },
  { unit: "Unit 7: Industrialization", word: "Secondary Sector", definition: "Manufacturing and processing of raw materials." },
  { unit: "Unit 7: Industrialization", word: "Tertiary Sector", definition: "Service-based economic activities." },
  { unit: "Unit 7: Industrialization", word: "Quaternary Sector", definition: "Knowledge-based industries like IT and research." },
  { unit: "Unit 7: Industrialization", word: "Quinary Sector", definition: "Highest-level decision-making roles." },
  { unit: "Unit 7: Industrialization", word: "Least Cost Theory", definition: "Industrial location theory that firms choose locations minimizing costs." },
  { unit: "Unit 7: Industrialization", word: "Break-of-Bulk Point", definition: "Location where transportation mode changes." },
  { unit: "Unit 7: Industrialization", word: "Gross Domestic Product (GDP)", definition: "Total value of goods and services produced in a country." },
  { unit: "Unit 7: Industrialization", word: "Gross National Income (GNI)", definition: "GDP plus income from abroad." },
  { unit: "Unit 7: Industrialization", word: "Gini Coefficient", definition: "Measure of income inequality (0 = equal, 1 = unequal)." },
  { unit: "Unit 7: Industrialization", word: "Literacy Rate", definition: "Percentage of population that can read and write." },
  { unit: "Unit 7: Industrialization", word: "Human Development Index (HDI)", definition: "Composite measure of development including income, education, and health." },
  { unit: "Unit 7: Industrialization", word: "Rostow's Stages of Growth", definition: "Model explaining economic development through five stages." },
  { unit: "Unit 7: Industrialization", word: "World Systems Theory", definition: "Division of world into core, semi-periphery, and periphery regions." },
  { unit: "Unit 7: Industrialization", word: "Dependency Theory", definition: "Idea that poorer countries are dependent on wealthier ones." },
  { unit: "Unit 7: Industrialization", word: "Comparative Advantage", definition: "Ability to produce goods at lower opportunity cost." },
  { unit: "Unit 7: Industrialization", word: "Free Trade", definition: "Trade without barriers like tariffs." },
  { unit: "Unit 7: Industrialization", word: "Neoliberalism", definition: "Economic policy favoring free markets and limited government intervention." },
  { unit: "Unit 7: Industrialization", word: "Outsourcing", definition: "Hiring external companies for production or services." },
  { unit: "Unit 7: Industrialization", word: "Offshoring", definition: "Moving production to another country." },
  { unit: "Unit 7: Industrialization", word: "Reshoring", definition: "Returning production to the home country." },
  { unit: "Unit 7: Industrialization", word: "Export Processing Zone (EPZ)", definition: "Area where goods are manufactured for export with tax incentives." },
  { unit: "Unit 7: Industrialization", word: "Special Economic Zone (SEZ)", definition: "Region with different economic rules to attract investment." },
  { unit: "Unit 7: Industrialization", word: "Free Trade Zone (FTZ)", definition: "Area where goods can be imported and exported without tariffs." },
  { unit: "Unit 7: Industrialization", word: "Post-Fordism", definition: "Flexible production system replacing mass production." },
  { unit: "Unit 7: Industrialization", word: "Fordism", definition: "System of mass production using assembly lines." },
  { unit: "Unit 7: Industrialization", word: "Agglomeration Economies", definition: "Benefits of businesses clustering together." },
  { unit: "Unit 7: Industrialization", word: "Containerization", definition: "Use of standardized containers for shipping goods." },
  { unit: "Unit 7: Industrialization", word: "Intermodal Transportation", definition: "Use of multiple transportation modes for shipping." },
  { unit: "Unit 7: Industrialization", word: "Footloose Industry", definition: "Industry not tied to a specific location." },
  { unit: "Unit 7: Industrialization", word: "Transnational Corporations (TNCs)", definition: "Companies operating in multiple countries." },
  { unit: "Unit 7: Industrialization", word: "Maquiladoras", definition: "Factories in Mexico producing goods for export." },
  { unit: "Unit 7: Industrialization", word: "Postindustrial Economy", definition: "Economy dominated by services and information." },
  { unit: "Unit 7: Industrialization", word: "Ecotourism", definition: "Tourism focused on environmental sustainability." },
  { unit: "Unit 7: Industrialization", word: "Rust Belt", definition: "Region of industrial decline." },
  { unit: "Unit 7: Industrialization", word: "Growth Poles", definition: "Areas that stimulate economic development." },
  { unit: "Unit 7: Industrialization", word: "Backwash Effects", definition: "Negative effects on surrounding regions caused by growth elsewhere." },
  { unit: "Unit 7: Industrialization", word: "Spread Effects", definition: "Positive diffusion of economic growth from a center to surrounding areas." },
]

export const SEEDED_ITEMS: VocabItem[] = raw.map((item, i) => ({
  ...item,
  id: `ap-${i}`,
  timesCorrect: 0,
  timesIncorrect: 0,
}))

// All unit names in order (derived from the seed data)
export const ALL_UNITS: string[] = Array.from(new Set(raw.map((i) => i.unit)))
